# To create the environment just run the command below
# conda-env create -f environment.yml
name: uqsa_tut
dependencies:
  - python
  - future
  - numpy
  - numba
  - matplotlib
  - scipy
  - sympy
  - statsmodels
  - jupyter
  - ipywidgets
  - xlwt
  - networkx
  - lxml
  - graphviz
  - h5py
  - pip
  - future
  - pip:
    - chaospy ==4.3.2
