# To create the environment just run the command below
# conda-env create -f environment.yml
name: starfish_dev
dependencies:
  - python =3.6
  - psutil
  - numpy
  - matplotlib
  - scipy
  - h5py
  - lxml >=3.4.2
  - pip
  - graphviz
  - future
  - sympy
  - pytest
  - pip:
    - chaospy ==2.2.2